[package]
name = "mao_core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
rand = "0.8.5"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
strum = { version = "0.26.3", features = ["derive"] }
